In [60]:
# Exercises XP

In [5]:

# 🌟 Exercise 1 : Array Creation and Manipulation
# Instructions

# Create a 1D NumPy array containing numbers from 0 to 9.

# Expected Output:


# array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

import numpy as np
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# 🌟 Exercise 2 : Type Conversion and Array Operations
# Instructions

# Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

# Expected Output:


# array([3, 2, 0, 1, 2])

list1 =  [3.14, 2.17, 0, 1, 2]
ar1 = np.array(list1)
ar1 = ar1.astype(int)
ar1

array([3, 2, 0, 1, 2])

In [27]:

# 🌟 Exercise 3 : Working with Multi-Dimensional Arrays
# Instructions

# Create a 3x3 NumPy array with values ranging from 1 to 9.

# Expected Output:


# array([[1, 2, 3],
#        [4, 5, 6],
#        [7, 8, 9]])
a1 = np.arange(1,10)
a1 = a1.reshape(3,3)
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
# 🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
# Instructions

# Create a 2D NumPy array of shape (4, 5) filled with random numbers.

# Expected Output:


# array([[0.56, 0.85, 0.01, 0.42, 0.68],
#        [0.22, 0.37, 0.73, 0.93, 0.39],
#        [0.44, 0.03, 0.87, 0.02, 0.83],
#        [0.78, 0.87, 0.98, 0.80, 0.46]])

a1 = np.random.rand(4, 5)
a1

array([[0.57635887, 0.02734367, 0.38548466, 0.59291999, 0.05979401],
       [0.18710766, 0.19453592, 0.29077594, 0.81265683, 0.96792645],
       [0.09956793, 0.37964398, 0.00107909, 0.87399406, 0.17567328],
       [0.55804855, 0.43216233, 0.27858109, 0.40315424, 0.50751257]])

In [32]:
# 🌟 Exercise 5 : Indexing Arrays
# Instructions

# Select the second row from a given 2D NumPy array.

# Expected Output:


# array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])
array[1,:]

array([20, 21, 22, 23, 24])

In [42]:
# 🌟 Exercise 6 : Reversing elements
# Instructions

# Reverse the order of elements in a given 1D NumPy array (first element becomes last).

# Expected Output:


# array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
a1 = np.arange(10)
a1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [44]:
# 🌟 Exercise 7 : Identity Matrix
# Instructions

# Create a 4x4 identity matrix using NumPy.

# Expected Output:


# array([[1., 0., 0., 0.],
#        [0., 1., 0., 0.],
#        [0., 0., 1., 0.],
#        [0., 0., 0., 1.]])
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [50]:
# 🌟 Exercise 8 : Simple Aggregate Funcs
# Instructions

# Find the sum and average of a given 1D array.

# Expected Output:


# Sum: 45, Average: 4.5
a3 = np.arange(10)
print(f'Sum: {a3.mean()}, Average: {a3.sum()}')

Sum: 4.5, Average: 45


In [55]:
# 🌟 Exercise 9 : Create Array and Change its Structure
# Instructions

# Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

# Expected Output:


# array([[ 1,  2,  3,  4,  5],
#        [ 6,  7,  8,  9, 10],
#        [11, 12, 13, 14, 15],
#        [16, 17, 18, 19, 20]])
a4 = np.arange(1,21)
a4 = a4.reshape(4,5)
a4

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [59]:
# 🌟 Exercise 10 : Conditional Selection of Values
# Instructions

# Extract all odd numbers from a given NumPy array.

# Expected Output:


# array([1, 3, 5, 7, 9])
a5 = np.arange(11)
a5[a5%2!=0]

array([1, 3, 5, 7, 9])