In [6]:
import numpy as np

# Creating a 1D array and a 2D array
a = np.array([0, 1, 2])
b = np.array([[0, 1, 2], [3, 4, 5]])

# Adding the 1D array to each row of the 2D array
result = a + b

print("1D Array:", a)
print("2D Array: ", b)
print("Broadcasted Addition: ", result)

1D Array: [0 1 2]
2D Array:  [[0 1 2]
 [3 4 5]]
Broadcasted Addition:  [[0 2 4]
 [3 5 7]]


In [8]:
import numpy as np

# Creating two arrays
a = np.array([[1], [2], [3]])
b = np.array([1, 2, 3])

# Adding the two arrays
result = a + b

print("Array a: ", a)
print("Array b:", b)
print("Broadcasted Addition: ", result)

Array a:  [[1]
 [2]
 [3]]
Array b: [1 2 3]
Broadcasted Addition:  [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [10]:
import numpy as np

# Creating two incompatible arrays
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2])

try:
    result = a + b
except ValueError as e:
    print("Error:", e)

Error: operands could not be broadcast together with shapes (2,3) (2,) 


In [12]:
import numpy as np

# Creating a 2D array and a 1D array
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])

# Element-wise multiplication
result = a * b

print("2D Array: ", a)
print("1D Array:", b)
print("Broadcasted Multiplication: ", result)

2D Array:  [[1 2 3]
 [4 5 6]]
1D Array: [1 2 3]
Broadcasted Multiplication:  [[ 1  4  9]
 [ 4 10 18]]


In [15]:
array = np.array([[1, 2, 3], [4, 5, 6]])
np.sum(array,axis=1)

array([ 6, 15])